namespace map_e1m1_1
{
	entity playerC;
	entity doctorC;
	float m1trainstate = 1;	

	float COLD = 0;
	float STARTUP = 1;
	float SLOWDOWN = 2;
	float STARTANDSTOP = 3;	

	float STATIONRIGHT = 1;
	float STATIONLEFT = 2;
	float STATIONBOTH = 3;

	float TRAIN_SPEED_FAST = 550;
	float TRAIN_SPEED_SLOW = 350;
	float TRAIN_SPEED_VERY_SLOW = 210;
	
	float AIRLOCK_MALFUNCTION = 0;

	float hideSubTimeTrain = 0;

	void SubtitlesRunningTrain()
	{
		while(hideSubTimeTrain > sys.getTime())		
		{			
			sys.waitFrame();
		}
		sys.hideSubtitles();
	}

	void ShowNPCSubtitlesTrain(string name, string titles, float duration)
	{
		PhobosShowSubtitle_e1m1_1(name, titles);
		hideSubTimeTrain = sys.getTime() + duration;
		sys.wait(duration);
		if(hideSubTimeTrain <= sys.getTime())
		{
			sys.hideSubtitles();
		}
		else
		{
			thread SubtitlesRunningTrain();
		}
	}

	void CharacterSays(entity characterEntity, string line)
	{
		sys.wait(characterEntity.startSoundShader(line, SND_CHANNEL_ANY));
	}

	void Beat(float delay)
	{
		sys.wait(delay);
	}

	float firstSpline = 0;

	void MoveTrainSpline(float distance, float desiredSpeed, float moveType, entity spline)
	{		
		float adTime = 5.546f;
		float acceleration = desiredSpeed / adTime;
		
		float accel = 0;
		float decel = 0;

		float totalAdTime = 0;
		float distanceTraveled = 0.0f;

		float adDis = 0.5f * acceleration * adTime * adTime;

		if( moveType == STARTUP || moveType == STARTANDSTOP )
		{
			$Looptrain1.accelTime(adTime);
			accel = 1;
			distanceTraveled += adDis;
			totalAdTime += adTime;
		}
		else
			$Looptrain1.accelTime(0);

		if( moveType == SLOWDOWN || moveType == STARTANDSTOP )		
		{
			$Looptrain1.decelTime(adTime);
			decel = 1;
			distanceTraveled += adDis;
			totalAdTime += adTime;
		}
		else
			$Looptrain1.decelTime(0);		

		float remainingDistance  = distance-distanceTraveled;
		float remainingTime = remainingDistance / desiredSpeed;
		float moveTime = totalAdTime + remainingTime;
				
		$Looptrain1.time(moveTime);

		$Looptrain1.startSpline(spline);
		if(firstSpline == 0)
			$Looptrain1.removeInitialSplineAngles();
		
		firstSpline++;

		float spentTime = 0;

		if(accel == 1)
		{
			$train_speaker.startSoundShader("sound/shav/general/pfft.ogg", SND_CHANNEL_BODY);
			$train_speaker2.stopSound(SND_CHANNEL_BODY2, false);
			sys.wait($train_speaker.startSoundShader("sound/shav/e1m1/train_speedup.ogg", SND_CHANNEL_BODY2) - 0.2);
		}

		$train_speaker2.startSoundShader("sound/shav/e1m1/train_travel.ogg", SND_CHANNEL_BODY2);
		
		if(remainingTime > 0.2)
		{			
			sys.wait(remainingTime + 0.2);
		}

		if(decel == 1)
		{		
			$train_speaker2.stopSound(SND_CHANNEL_BODY2, false);
			//sys.print("deceleration");
			sys.trigger($train_brakes);
			sys.wait($train_speaker.startSoundShader("sound/shav/e1m1/train_slowdown.ogg", SND_CHANNEL_BODY2) - 0.2);
			$train_speaker.startSoundShader("sound/shav/general/pfft.ogg", SND_CHANNEL_BODY);
			sys.wait(.1);
			$train_speaker2.startSoundShader("sound/shav/e1m1/train_idle.ogg", SND_CHANNEL_BODY2);
		}		

		sys.waitFor($Looptrain1);
	}

	void RotateTrain(entity anchor)
	{
		$Looptrain1.bind(anchor);
		anchor.rotateOnce('0 -90 0');
		sys.waitFor(anchor);
		$Looptrain1.unbind();		
	}

	void TrainDoorAlarm(float side, entity station_speaker)
	{
		/*
		sys.wait(4);

		float d = 0;
		if( side == STATIONLEFT)
		{
			//start sound
			sys.trigger($train_left_speaker3);
			sys.trigger($train_left_speaker);
			
			while(d < 3)
			{			
				sys.trigger($train_left_relay1);

				sys.wait(.7);
				sys.trigger($train_left_relay1);

				sys.wait(.35);
				sys.trigger($train_left_relay2);

				sys.wait(.5);
				sys.trigger($train_left_relay2);

				sys.wait(.45);
				d++;
			}		
		
			//start stressful sound
			sys.trigger($train_left_speaker2);			

			sys.wait(.2);

			//stop sound
			sys.trigger($train_left_speaker);
		
			sys.trigger(station_speaker);

			d = 0;
			while(d < 2)
			{			
				sys.trigger($train_left_relay1);
				sys.trigger($train_left_relay2);

				sys.wait(.7);
				sys.trigger($train_left_relay1);
				sys.trigger($train_left_relay2);
				sys.wait(.35);
			
				sys.trigger($train_left_relay1);
				sys.trigger($train_left_relay2);

				sys.wait(.5);
				sys.trigger($train_left_relay1);
				sys.trigger($train_left_relay2);

				sys.wait(.45);
				d++;
			}
			
			sys.trigger($train_left_speaker3);
			sys.trigger($train_left_speaker2);
		}

		if( side == STATIONRIGHT)
		{
			//start sound
			sys.trigger($train_right_speaker3);
			sys.trigger($train_right_speaker);
			d = 0;
			while(d < 3 * 2)
			{			
				sys.trigger($train_right_relay1);

				sys.wait(.7);
				sys.trigger($train_right_relay1);

				sys.wait(.35);
				sys.trigger($train_right_relay2);

				sys.wait(.5);
				sys.trigger($train_right_relay2);

				sys.wait(.45);
				d++;
			}		
		
			//start stressful sound
			sys.trigger($train_right_speaker2);			
			sys.wait(.1);

			//stop sound
			sys.trigger($train_right_speaker);
		
			sys.trigger(station_speaker);

			d = 0;
			while(d < 1 * 3)
			{			
				sys.trigger($train_right_relay1);
				sys.trigger($train_right_relay2);

				sys.wait(.7);
				sys.trigger($train_right_relay1);
				sys.trigger($train_right_relay2);
				sys.wait(.35);
			
				sys.trigger($train_right_relay1);
				sys.trigger($train_right_relay2);

				sys.wait(.5);
				sys.trigger($train_right_relay1);
				sys.trigger($train_right_relay2);

				sys.wait(.45);
				d++;
			}
			
			sys.trigger($train_right_speaker3);
			sys.trigger($train_right_speaker2);
		}
		*/
	}

	void DockTrain(float stationSide, entity station_speaker)
	{
		// Open Doors
		if( stationSide == STATIONLEFT || stationSide == STATIONBOTH)
		{
			$Looptrain1_OuterDoor1.open();
			$train_player_clip.hide();
		}

		if( stationSide == STATIONRIGHT || stationSide == STATIONBOTH)
		{
			$Looptrain1_OuterDoor2.open();
			$train_player_clip.hide();
		}		
	}

	void UndockTrain(float stationSide, entity station_speaker)
	{
		//TrainDoorAlarm(stationSide, station_speaker);

		// Close Doors
		if( stationSide == STATIONLEFT || stationSide == STATIONBOTH)
		{
			$Looptrain1_OuterDoor1.close();
			$train_player_clip.show();
		}

		if( stationSide == STATIONRIGHT || stationSide == STATIONBOTH)
		{
			$Looptrain1_OuterDoor2.close();
			$train_player_clip.show();
		}

		sys.wait(3);
	}

	void ToggleAirlockState()
	{
		AIRLOCK_MALFUNCTION = 1;
	}
	
	float firstRun = 1;

	void RunAirlock(float number)
	{
		if(number == 4 && firstRun == 1)
		{
			sys.trigger($remove_dumb_passengers);
			firstRun = 0;
		}

		entity speaker_center = sys.getEntity("airlock" + number + "_speaker_center");
		entity speaker_left = sys.getEntity("airlock" + number + "_speaker_left");
		entity speaker_left2 = sys.getEntity("airlock" + number + "_speaker_left2");
		entity speaker_right = sys.getEntity("airlock" + number + "_speaker_right");
		entity speaker_right2 = sys.getEntity("airlock" + number + "_speaker_left");
		entity light1_relay = sys.getEntity("airlock" + number + "_light1_relay");
		entity light2_relay = sys.getEntity("airlock" + number + "_light2_relay");
		entity light3_relay = sys.getEntity("airlock" + number + "_light3_relay");
		entity light4_relay = sys.getEntity("airlock" + number + "_light4_relay");
		entity flare1 = sys.getEntity("airlock" + number + "_light1_flare");
		entity flare2 = sys.getEntity("airlock" + number + "_light2_flare");
		entity flare3 = sys.getEntity("airlock" + number + "_light3_flare");
		entity flare4 = sys.getEntity("airlock" + number + "_light4_flare");
		
		
		if(AIRLOCK_MALFUNCTION == 1)
		{
		
			sys.trigger(speaker_center);
			sys.wait(1.5);

			thread crossFadeEnt (flare1, '0 0 0', '0 0.82 1', .125);
			sys.trigger(light1_relay);
			sys.trigger(speaker_right);
			sys.wait(.5);

			thread crossFadeEnt (flare1, '0 0.82 1', '0 0 0', .125);
			thread crossFadeEnt (flare2, '0 0 0', '0 0.82 1', .125);
			sys.trigger(light1_relay);
			sys.trigger(speaker_right2);
			sys.trigger(light2_relay);
			sys.trigger(speaker_left);
			sys.wait(2.5);
			
			sys.trigger($func_fx_206);
			sys.trigger($decon_light_break_spkr);
			sys.wait(1);
			sys.trigger($airlock_lights_off);
			
			sys.wait(6.5);
			
		} else if(AIRLOCK_MALFUNCTION == 0){
		
			sys.trigger(speaker_center);
			sys.wait(1.5);

			thread crossFadeEnt (flare1, '0 0 0', '0 0.82 1', .125);
			sys.trigger(light1_relay);
			sys.trigger(speaker_right);
			sys.wait(.5);

			thread crossFadeEnt (flare1, '0 0.82 1', '0 0 0', .125);
			thread crossFadeEnt (flare2, '0 0 0', '0 0.82 1', .125);
			sys.trigger(light1_relay);
			sys.trigger(speaker_right2);
			sys.trigger(light2_relay);
			sys.trigger(speaker_left);
			sys.wait(.5);
			
			thread crossFadeEnt (flare2, '0 0.82 1', '0 0 0', .125);
			thread crossFadeEnt (flare3, '0 0 0', '0 0.82 1', .125);
			sys.trigger(light2_relay);
			sys.trigger(speaker_left2);
			sys.trigger(light3_relay);
			sys.trigger(speaker_right);
			sys.wait(.5);

			thread crossFadeEnt (flare3, '0 0.82 1', '0 0 0', .125);
			thread crossFadeEnt (flare4, '0 0 0', '0 0.82 1', .125);
			sys.trigger(light3_relay);
			sys.trigger(speaker_right2);
			sys.trigger(light4_relay);
			sys.trigger(speaker_left);
			sys.wait(.5);

			thread crossFadeEnt (flare4, '0 0.82 1', '0 0 0', .125);
			sys.trigger(light4_relay);
			sys.trigger(speaker_left2);
			
			sys.wait(.5);
		}
	}

	void AnnounceUpcomingStation(float station)
	{
		sys.wait($train_intercom_speaker.startSoundShader("sound/vo/e1m1/intercomtrainarrivingat.ogg", SND_CHANNEL_BODY2));
		if( station == 1)
		{						
			$train_intercom_speaker.startSoundShader("sound/vo/e1m1/intercomtrainmarscity.ogg", SND_CHANNEL_BODY2);
		}
		else if (station == 2)
		{
			$train_intercom_speaker.startSoundShader("sound/vo/e1m1/intercomtrainrecreation.ogg", SND_CHANNEL_BODY2);
		}
		else if(station == 3)
		{
			$train_intercom_speaker.startSoundShader("sound/vo/e1m1/intercomtrainmarinecommand.ogg", SND_CHANNEL_BODY2);
		}
	}

	float loop = 1;

	void AnnounceMarsCity()
	{
		AnnounceUpcomingStation(1);
	}

	void AnnounceRecreation()
	{
		if(loop == 2)
			AnnounceUpcomingStation(2);
	}

	void AnnounceMarineCommand()
	{
		AnnounceUpcomingStation(3);
	}	

	void TestExitTrain()
	{			
		thread MoveTrainSpline(1568+1218+1848, TRAIN_SPEED_VERY_SLOW, STARTUP, $spline_final_trip6);

		sys.wait(15.73);

		sys.trigger($SpeakerOminousHorn);

		sys.wait(.5);

		sys.trigger($train_brakes);
		$train_brakes.fadeSound(SND_CHANNEL_ANY, 10, .125);

		sys.wait(.5);
		
		sys.trigger($func_earthquake_7);
			sys.fadeOut('0 0 0', 0.05);
			sys.trigger($SpeakerTrainFly);

			sys.wait(.05);
			sys.trigger($TrainAlternateCam);

			sys.wait(.5);			

			sys.fadeIn('0 0 0', 0.125);			
			sys.trigger($SpeakerTrainFly);

			sys.wait(.125);
			sys.trigger($TrainAlternateCam);

			sys.wait(.25);

			sys.trigger($func_earthquake_8);

			sys.fadeOut('0 0 0', 0.05);			
			sys.trigger($SpeakerTrainFly);

			sys.wait(.05);
			sys.trigger($TrainAlternateCam);
			
			sys.trigger($speaker_clutter);
			
			sys.wait(.5);

			sys.trigger($func_earthquake_6);			

			sys.fadeIn('0 0 0', 0.125);			
			sys.trigger($SpeakerTrainFly);

			sys.wait(.125);
			sys.trigger($TrainAlternateCam);

			sys.wait(.25);
			
			sys.fadeOut('0 0 0', 0.05);			
			sys.trigger($SpeakerTrainFly);

			sys.trigger($func_earthquake_5);

			sys.wait(.05);
			sys.trigger($TrainAlternateCam);

			sys.wait(.5);

			sys.fadeIn('0 0 0', 0.125);			
			sys.trigger($SpeakerTrainFly);

			sys.wait(.125);
			sys.trigger($TrainAlternateCam);

			sys.wait(.25);

			sys.fadeOut('0 0 0', 0.05);			
			sys.trigger($SpeakerTrainFly);

			sys.wait(.05);
			sys.trigger($TrainAlternateCam);			

			sys.wait(1);			
			sys.trigger($SpeakerCrickets);

			sys.wait(10);

			thread ShowNPCSubtitlesTrain("Girl", "Let it burn.", 2);
			sys.trigger($SpeakerLetItBurn);
			sys.wait(3);
			//sys.trigger($SpeakerEndFlash);
			sys.wait(4);

			// Map load
			sys.trigger($target_endlevel_1);
	}

	void DisembarkFromMarineCommand2()
	{
		UndockTrain(STATIONLEFT, $station_marinecommand_leaving_speaker);		

		MoveTrainSpline(1472+1218+1856, TRAIN_SPEED_SLOW, STARTANDSTOP, $spline_final_trip1﻿);
		
		RunAirlock(3);

		MoveTrainSpline(1376+1218+1400, TRAIN_SPEED_SLOW, STARTANDSTOP, $spline_final_trip2﻿);

		RunAirlock(4);

		MoveTrainSpline(1632 + 4784, TRAIN_SPEED_FAST, STARTANDSTOP, $spline_final_trip3);

		RunAirlock(1);

		MoveTrainSpline(1472 + 448, TRAIN_SPEED_SLOW, STARTANDSTOP, $spline_final_trip4);		

		ToggleAirlockState();
	}
	
	void FinishTrainRide()
	{
		MoveTrainSpline(696+1218+1664, TRAIN_SPEED_VERY_SLOW, STARTANDSTOP,$spline_final_trip5);

		RunAirlock(2);
		
		TestExitTrain();
	}	

	float TrainReadyForFinalTrip = 0;

	void DisembarkFromRecreation()
	{	
		thread ShowNPCSubtitlesTrain("AP", "Mars City station locked down until further notice. It is now possible to disembark at Recreation station.", 7);
		
		sys.trigger($Disembarker);

		while(TrainReadyForFinalTrip == 0)
		{
			sys.wait(1);
		}

		sys.trigger($trigger_relay_607);

		UndockTrain(STATIONRIGHT, $light_63111);

		sys.trigger($trigger_multiple_18);

		sys.trigger($relay_mcity_triggers);

		// Move to Marine Command
		MoveTrainSpline(8960 - 3552, TRAIN_SPEED_FAST, SLOWDOWN,$spline_marine_command2);
			
		// Dock
		DockTrain(STATIONLEFT, $station_marinecommand_leaving_speaker);
	}

	void DisembarkFromMarineCommand1()
	{
		UndockTrain(STATIONLEFT, $station_marinecommand_leaving_speaker);

		// Move to Airlock 3
		MoveTrainSpline(1856+1218+1472,TRAIN_SPEED_SLOW, STARTANDSTOP, $spline_depart_marine_command);		

		RunAirlock(3);

		MoveTrainSpline(1376+1218+1400,TRAIN_SPEED_FAST * 10, STARTANDSTOP, $spline_recreation1_empty);		
		MoveTrainSpline(1632+4784,TRAIN_SPEED_FAST * 10, STARTANDSTOP, $spline_recreation2_empty);
		MoveTrainSpline(2616+1218+1664,TRAIN_SPEED_FAST * 10, STARTANDSTOP, $spline_recreation3_empty);
		MoveTrainSpline(1568+1218+3552,TRAIN_SPEED_FAST * 10, STARTANDSTOP, $spline_recreation4_empty);

		// Dock
		DockTrain(STATIONRIGHT, $light_63111);

		TrainReadyForFinalTrip = 1;
	}
	
	void DisembarkFromMarsCity()
	{
	// One arc: 1218

		UndockTrain(STATIONLEFT, $station_mcity_leaving_speaker);
		
		$postscanner_spkr.fadeSound(SND_CHANNEL_ANY, -60, 8);
		
		// Move from station to airlock 1
		MoveTrainSpline(4784, TRAIN_SPEED_FAST, STARTANDSTOP, $spline_depart_mars_city);	
		
		RunAirlock(1);
		MoveTrainSpline(5370, TRAIN_SPEED_SLOW, STARTANDSTOP, $spline_metropolis);		

		RunAirlock(2);		

		$postscanner_spkr.stopSound(SND_CHANNEL_ANY, false);

		MoveTrainSpline(1504+1218+8896, TRAIN_SPEED_SLOW, STARTANDSTOP, $spline_marine_command);

		// Dock
		DockTrain(STATIONLEFT, $station_marinecommand_leaving_speaker);
	}

	float trainCalled = 0;

	void AWildTrainAppears()
	{
		if(trainCalled == 0)
		{
			trainCalled = 1;		

			MoveTrainSpline(1632, TRAIN_SPEED_SLOW, SLOWDOWN, $spline_mars_city);
			DockTrain(STATIONLEFT, $station_mcity_leaving_speaker);
		}
	}	

	void InitTrain()
	{
		MoveTrainSpline(1008, TRAIN_SPEED_FAST*10, COLD, $spline_init_move);		
	}
}