/***********************************************************************

doom_main.script

This is the main script that is loaded before any level scripts load.

***********************************************************************/

#include "script/phobos_events.script"

// base defines and util functions
#include "script/doom_defs.script"
#include "script/doom_events.script"
#include "script/doom_util.script"
#include "script/weapon_base.script"
#include "script/ai_base.script"

// weapons
#include "script/weapon_fists.script"
#include "script/weapon_pistol.script"
#include "script/weapon_shotgun.script"
#include "script/weapon_machinegun.script"
#include "script/weapon_chaingun.script"
#include "script/weapon_handgrenade.script"
#include "script/weapon_plasmagun.script"
#include "script/weapon_rocketlauncher.script"
#include "script/weapon_bfg.script"
#include "script/weapon_chainsaw.script"
#include "script/weapon_flashlight.script"
#include "script/weapon_pda.script"

// maps

// ai
#include "script/ai_monster_base.script"
#include "script/ai_monster_zombie_base.script"
#include "script/ai_monster_demon_imp.script"
#include "script/ai_monster_demon_maggot.script"
#include "script/ai_monster_demon_pinky.script"
#include "script/ai_monster_zombie.script"
#include "script/ai_monster_zombie_morgue.script"
#include "script/ai_monster_zombie_sawyer.script"
#include "script/ai_monster_zombie_bernie.script"
#include "script/ai_monster_zombie_commando_cgun.script"
#include "script/ai_monster_zombie_commando_tentacle.script"
#include "script/ai_monster_zombie_security_pistol.script"
#include "script/ai_character.script"
#include "script/ai_character_prone.script"
#include "script/ai_character_sentry.script"
#include "script/ai_player.script"

// map specific character scripts

// map scripts

// test scripts
#include "script/ai_follower.script"

void doom_main() {
	sys.print( "Entering doom_main()\n");

	//
	// Do any script setup here
	//

	sys.print( "Exiting doom_main()\n" );
}
